version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: daily
    groups:
      maven-minor-and-patch-updates:
        update-types:
          - minor
          - patch
      maven-major-updates:
        update-types:
          - major
    commit-message:
      prefix: "Maven Update"

  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: daily
    groups:
      gradle-minor-and-patch-updates:
        update-types:
          - minor
          - patch
      gradle-major-updates:
        update-types:
          - major
    commit-message:
      prefix: "Gradle Update"
